name: Auto Click Website at 2AM VN

on:
  schedule:
    - cron: '0 19 * * *'   # Lịch UTC → 19:00 UTC = 2:00AM VN
  workflow_dispatch:        # Cho phép bạn chạy thủ công

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Run Puppeteer script
        run: node index.js

      - name: Done
        run: echo "✅ Đã chạy xong script Puppeteer!"
